# Generated by Django 4.2.7 on 2023-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isMe',
            field=models.BooleanField(default=True),
        ),
    ]
